import { db } from '@/db';
import { adoptionGuides } from '@/db/schema';

async function main() {
    const sampleGuides = [
        // Procedure guides (3)
        {
            title: 'Step-by-Step Adoption Process',
            content: 'The pet adoption process begins with understanding what to expect at every stage. First, you will need to browse available pets either online or by visiting local animal shelters. Once you find a pet that matches your lifestyle and preferences, you will submit an adoption application providing details about your living situation, experience with pets, and why you want to adopt.\n\nAfter your application is reviewed, the shelter will schedule a meeting with you to discuss your expectations and answer any questions. This is followed by a home visit where shelter staff will assess if your home environment is suitable for the pet you wish to adopt. The home visit ensures that your living space is safe, secure, and appropriate for the specific animal.\n\nOnce approved, you will sign an adoption contract and pay the adoption fee, which typically covers vaccinations, spaying/neutering, and microchipping. The shelter will provide you with all medical records, care instructions, and ongoing support. Remember that adoption is a commitment, and shelters want to ensure the best match for both you and the pet.\n\nThe entire process can take anywhere from a few days to several weeks, depending on the shelter and the thoroughness of their screening process. Be patient and honest throughout the process, as shelters are looking for responsible, committed pet owners who will provide loving homes for their animals.',
            category: 'procedure',
            orderIndex: 1,
            createdAt: new Date(),
        },
        {
            title: 'Home Visit Guidelines',
            content: 'A home visit is a crucial part of the adoption process and should not be viewed as intimidating. Shelter representatives conduct home visits to ensure the safety and well-being of the animals they place. During the visit, staff will assess your living space to verify that it matches what you described in your application and is suitable for the specific pet you want to adopt.\n\nBefore the visit, prepare your home by ensuring it is clean and safe. Check that there are no hazardous materials accessible to pets, such as toxic plants, exposed electrical wires, or small objects that could be swallowed. If you are adopting a dog, make sure your yard is securely fenced with no gaps or holes through which a pet could escape. For cats, ensure windows have secure screens and there are no dangerous hiding spots.\n\nDuring the home visit, the shelter representative will discuss your daily routine, work schedule, and how you plan to integrate the pet into your life. They may ask to see where the pet will sleep, eat, and spend most of their time. Be honest and open about any concerns or questions you have. This is also an opportunity for you to ask questions about the specific pet and get professional advice on preparation.\n\nRemember that the home visit is not meant to judge your lifestyle but to ensure a successful adoption. Shelter staff want to place animals in homes where they will thrive, and the home visit helps identify any potential issues that could be addressed before adoption. Most home visits last 30-60 minutes and are conducted in a friendly, supportive manner.',
            category: 'procedure',
            orderIndex: 2,
            createdAt: new Date(),
        },
        {
            title: 'Application Review and Interview Process',
            content: 'The adoption application is your first step toward bringing a new pet into your life. Most shelters require detailed applications that ask about your living situation, pet ownership history, household members, and lifestyle. Take your time filling out the application and be thorough and honest in your responses. Incomplete or misleading information can delay the process or result in application denial.\n\nAfter submitting your application, shelter staff will review it carefully, typically within 2-5 business days. They will verify information such as landlord approval for pet ownership, veterinary references if you have owned pets before, and personal references. Some shelters may also conduct background checks to ensure animals are going to responsible homes. This thorough vetting process exists to protect the animals and ensure successful adoptions.\n\nOnce your application is preliminarily approved, you will be invited for an interview with adoption counselors. This interview is a two-way conversation where the shelter learns more about you and your expectations, and you learn more about the specific pet and what to expect. Come prepared with questions about the pet\'s history, temperament, medical needs, and behavioral characteristics. Adoption counselors appreciate engaged, curious prospective adopters who want to make informed decisions.\n\nDuring the interview, discuss honestly any concerns about behavior, training needs, or adjustment periods. Adoption counselors can provide valuable insights and resources to help you succeed as a pet owner. They may also suggest different pets if they believe another animal would be a better fit for your situation. Remember, the goal is a lifelong match, not just completing an adoption.',
            category: 'procedure',
            orderIndex: 3,
            createdAt: new Date(),
        },
        // Requirements guides (4)
        {
            title: 'Eligibility Criteria for Adoption',
            content: 'Understanding eligibility criteria before starting the adoption process helps set realistic expectations. Most shelters require adopters to be at least 18 or 21 years old with valid identification. You must be able to make the long-term commitment required for pet ownership, which can span 10-20 years depending on the animal. Financial stability is important, as pet ownership involves ongoing costs for food, veterinary care, supplies, and emergencies.\n\nIf you rent your home, you must have written permission from your landlord or property management allowing pets. Many adoption applications are denied because renters do not verify this information in advance. Homeowners should ensure their property is suitable for the type and size of pet they wish to adopt. Some shelters have specific requirements for certain breeds or species, such as requiring fenced yards for large dogs.\n\nPrior pet ownership experience is viewed favorably but is not always required, especially for adopters willing to learn and commit to training. However, if you have surrendered pets to shelters in the past or have negative veterinary references, this may impact your application. Shelters want to ensure animals go to homes where they will be properly cared for throughout their lives.\n\nAll household members must agree to the adoption and understand the commitment involved. Shelters often require all family members to meet the pet before finalizing adoption. If you have existing pets, they may need to meet the new pet to ensure compatibility. Being honest about your lifestyle, experience, and expectations helps shelters match you with the right pet and increases the likelihood of a successful, lasting adoption.',
            category: 'requirements',
            orderIndex: 1,
            createdAt: new Date(),
        },
        {
            title: 'Living Space Requirements',
            content: 'Your living space plays a crucial role in determining which pets are suitable for adoption. The size and layout of your home, whether you have outdoor space, and the overall environment all factor into adoption decisions. Different animals have different space requirements, and shelters carefully evaluate if your home can meet those needs. For example, large, active dog breeds need more space than small dogs or cats.\n\nFor dog adoption, outdoor space is often a key consideration. While not all dogs require a yard, many shelters prefer that larger breeds have access to secure outdoor areas for exercise and bathroom needs. If you have a yard, it must be securely fenced with appropriate height and no gaps. Check for escape routes, toxic plants, and potential hazards before bringing a dog home. Apartment dwellers can still adopt dogs, but may need to demonstrate access to nearby parks and a plan for regular exercise.\n\nCats generally adapt well to various living spaces, including apartments, as long as they have vertical territory like cat trees, safe window perches, and enrichment opportunities. However, if you plan to allow outdoor access, you must ensure the environment is safe. Many shelters now encourage or require indoor-only adoption contracts for cats to protect them from traffic, predators, and diseases.\n\nIndoor living space should be safe and comfortable for pets. Remove or secure hazardous items, ensure adequate temperature control, and create designated spaces for feeding, sleeping, and litter boxes. Consider noise levels, especially in apartments, and how they might affect anxious animals. Your living space should allow pets to engage in natural behaviors while being safely contained and protected.',
            category: 'requirements',
            orderIndex: 2,
            createdAt: new Date(),
        },
        {
            title: 'Financial Preparedness Checklist',
            content: 'Pet ownership involves significant financial commitment beyond the initial adoption fee. Before adopting, honestly assess your budget to ensure you can afford routine and emergency pet care. The adoption fee typically ranges from $50-$500 and usually includes initial vaccinations, spaying/neutering, and microchipping. However, this is just the beginning of pet-related expenses.\n\nRoutine expenses include high-quality food ($30-$100 monthly), preventive veterinary care ($200-$500 annually), flea/tick prevention ($100-$300 annually), and basic supplies like leashes, collars, toys, and bedding ($200-$500 initially, then $50-$200 annually). Cat owners must budget for litter ($15-$30 monthly). These costs vary based on pet size, health needs, and product quality, but they are consistent, ongoing expenses.\n\nVeterinary emergencies and unexpected illnesses can cost hundreds to thousands of dollars. Responsible pet owners should have an emergency fund of at least $1,000-$2,000 or consider pet insurance, which typically costs $30-$70 monthly for dogs and $15-$40 for cats. Insurance can help manage costs for accidents, illnesses, and chronic conditions. Some policies also cover routine care.\n\nAdditional costs may include training classes ($100-$300), boarding or pet sitting during travel ($25-$75 daily), grooming for certain breeds ($30-$90 per session), and dental care ($300-$1,000 annually). If you move, pet deposits and monthly pet rent can add $200-$500 to housing costs. Calculate these expenses realistically and ensure pet ownership fits comfortably within your budget before adopting.',
            category: 'requirements',
            orderIndex: 3,
            createdAt: new Date(),
        },
        {
            title: 'Time Commitment and Lifestyle Assessment',
            content: 'Pet ownership requires substantial time commitment that extends far beyond feeding and basic care. Before adopting, honestly evaluate your daily schedule, work commitments, travel frequency, and lifestyle to ensure you can meet a pet\'s needs. Dogs typically require 2-4 hours of attention daily, including walks, play, training, and companionship. Cats are often more independent but still need daily interaction, play, and mental stimulation.\n\nConsider your work schedule carefully. Puppies and kittens require extensive time for housetraining, socialization, and bonding. Adult pets adjusting to new homes need patience and consistent routines. If you work long hours, travel frequently, or have unpredictable schedules, ensure you have reliable backup care through pet sitters, doggy daycare, or friends and family. Leaving pets alone for extended periods can lead to behavioral problems, anxiety, and health issues.\n\nYour lifestyle activities should align with pet ownership responsibilities. Active individuals who enjoy hiking, running, or outdoor activities may be well-suited for energetic dog breeds. Homebodies might prefer cats or lower-energy dogs. However, remember that all pets need exercise, mental stimulation, and social interaction. Evaluate whether your hobbies, social life, and routine activities can accommodate a pet or if adjustments are necessary.\n\nPet ownership also impacts major life decisions. Moving becomes more complicated with pets, as you must find pet-friendly housing. Vacations require either bringing pets along or arranging care. Career opportunities involving relocation or extensive travel may need reconsideration. Children, new relationships, and other life changes affect pets and must be managed thoughtfully. Assess your current life stage and anticipated changes over the next 10-20 years to ensure you can commit to pet ownership throughout the animal\'s lifetime.',
            category: 'requirements',
            orderIndex: 4,
            createdAt: new Date(),
        },
        // Documentation guides (3)
        {
            title: 'Required Documents for Adoption',
            content: 'Successful pet adoption requires preparing several important documents before beginning the process. Having these documents ready demonstrates your preparedness and can significantly expedite the adoption timeline. The specific requirements vary by shelter, but most organizations have similar documentation needs to ensure responsible pet placement.\n\nPersonal identification is essential for all adopters. Bring a valid government-issued photo ID such as a driver\'s license, state ID, or passport. The name and address on your ID should match your adoption application. If you recently moved, bring additional proof of current address like a utility bill, lease agreement, or mortgage statement. Some shelters verify that you live where you claim to live to ensure pets go to actual, stable homes.\n\nFor renters, landlord approval documentation is critical and often the most commonly overlooked requirement. Contact your landlord or property management before applying to adopt and obtain written permission for pet ownership. This should specify allowed pet types, sizes, and any breed restrictions. Some shelters accept lease agreements that explicitly allow pets, while others require a separate letter from the landlord. Without this documentation, rental applicants face automatic denial regardless of other qualifications.\n\nAdditional documents may include veterinary records if you currently own or previously owned pets, demonstrating responsible pet care history. Personal and professional references may need contact information for verification. Some shelters require proof of income or employment to ensure financial stability. If adopting for a family, bring documentation showing all household members consent to the adoption. Preparing these documents in advance shows the shelter you are organized, responsible, and serious about adoption.',
            category: 'documentation',
            orderIndex: 1,
            createdAt: new Date(),
        },
        {
            title: 'Adoption Contract and Legal Agreement',
            content: 'The adoption contract is a legally binding agreement between you and the shelter that outlines responsibilities, expectations, and terms of the adoption. Read this document carefully before signing, and don\'t hesitate to ask questions about any clauses you don\'t understand. This contract protects both you and the animal by clearly defining obligations and recourse if problems arise.\n\nMost adoption contracts require you to provide proper care including adequate food, water, shelter, veterinary care, and humane treatment. Many contracts prohibit declawing cats or using specific training methods. You typically agree to maintain current vaccinations, provide annual veterinary checkups, and spay/neuter if not already done. Failure to comply with these terms may result in the shelter reclaiming the animal.\n\nMany shelters include a return policy in adoption contracts, requiring you to return the pet to the shelter if you can no longer care for them rather than rehoming independently or surrendering to another facility. This ensures the shelter can track their animals and provide continuity of care. Some contracts also grant shelters the right to conduct follow-up visits or require updates on the pet\'s welfare for a specified period after adoption.\n\nThe contract will specify the adoption fee and what it covers, such as vaccinations, spaying/neutering, microchipping, and any medical treatments the pet has received. It may include information about known behavioral or health issues and your acknowledgment of these conditions. Some contracts require you to take pets to training classes or work with behavioral specialists if recommended. Understanding and agreeing to these terms before signing prevents future disputes and ensures you are fully prepared for the responsibilities of pet ownership.',
            category: 'documentation',
            orderIndex: 2,
            createdAt: new Date(),
        },
        {
            title: 'Medical Records and Health Documentation',
            content: 'Understanding and maintaining your adopted pet\'s medical records is crucial for providing proper ongoing care. At adoption, the shelter will provide you with comprehensive health documentation detailing all medical treatments, vaccinations, and health assessments the pet has received. Review these records carefully with shelter staff to understand your pet\'s health history and immediate care needs.\n\nVaccination records are among the most important documents you will receive. These show which vaccines the pet has received and when boosters are due. Dogs typically receive vaccines for rabies, distemper, parvovirus, and bordetella. Cats receive vaccines for rabies, feline distemper, and feline leukemia. Maintaining current vaccinations protects your pet from serious diseases and is often legally required for rabies. Schedule a veterinary appointment shortly after adoption to continue the vaccination schedule and establish care with a regular veterinarian.\n\nMedical records should include spay/neuter documentation, microchip registration information, and records of any illnesses, injuries, or treatments the pet received at the shelter. If the pet is on medication or has chronic health conditions, the shelter will provide detailed instructions and prescriptions. Some pets may require special diets, ongoing treatments, or follow-up veterinary visits, and this information will be clearly documented.\n\nEstablish a relationship with a veterinarian immediately after adoption. Bring all shelter-provided medical records to your first veterinary appointment so your vet has a complete health history. Many vets offer free post-adoption checkups to assess your new pet\'s health and address any concerns. Keep all medical records organized in a folder or digital system, and update them regularly with new vaccinations, treatments, and checkups. This documentation is essential for boarding facilities, pet sitters, and emergency veterinary care.',
            category: 'documentation',
            orderIndex: 3,
            createdAt: new Date(),
        },
        // Post-adoption guides (4)
        {
            title: 'First 30 Days with Your New Pet',
            content: 'The first month with your newly adopted pet is a critical adjustment period for both you and the animal. Understanding what to expect and how to support your pet through this transition helps build a strong foundation for your relationship. Most pets need 3-6 months to fully settle into new homes, but the first 30 days are particularly important for establishing routines, building trust, and addressing initial behavioral challenges.\n\nDuring the first few days, give your pet space to decompress and adjust to their new environment. Many animals experience stress from the shelter environment and transition, leading to behaviors like hiding, reduced appetite, or accidents. Create a safe, quiet space where your pet can retreat when overwhelmed. Introduce family members gradually and keep initial interactions calm and positive. Resist the urge to invite friends and neighbors over to meet your new pet immediately.\n\nEstablish consistent routines for feeding, walks, playtime, and sleep from day one. Pets thrive on predictability, and routines help reduce anxiety while teaching them what to expect in their new home. Use positive reinforcement training methods to teach basic commands and household rules. Be patient with housetraining accidents and behavioral issues, understanding that these are normal adjustment responses, not permanent problems.\n\nMonitor your pet\'s health closely during the first month. Schedule a veterinary checkup within the first week to address any health concerns and establish preventive care. Watch for signs of illness such as lethargy, loss of appetite, vomiting, or diarrhea. Gradually introduce new foods if changing diets, mixing old and new food over 7-10 days to prevent digestive upset. Document your pet\'s behaviors, preferences, and any concerns to discuss with your veterinarian or a professional trainer if needed.',
            category: 'post-adoption',
            orderIndex: 1,
            createdAt: new Date(),
        },
        {
            title: 'Healthcare and Vaccination Schedule',
            content: 'Maintaining proper healthcare and vaccination schedules is essential for keeping your adopted pet healthy throughout their life. Work with a veterinarian to establish a comprehensive preventive care plan tailored to your pet\'s age, health status, and lifestyle. Regular veterinary visits allow early detection and treatment of health issues, potentially saving your pet\'s life and reducing long-term medical costs.\n\nCore vaccines protect against serious, potentially fatal diseases and are recommended for all pets. Dogs should receive rabies, distemper, parvovirus, and adenovirus vaccines, with initial puppy series starting at 6-8 weeks and boosters every 1-3 years for adults. Cats need rabies, feline distemper (panleukopenia), feline herpesvirus, and calicivirus vaccines, also starting in kittenhood with adult boosters every 1-3 years. Your veterinarian may recommend additional non-core vaccines based on lifestyle and exposure risks, such as bordetella, leptospirosis, or feline leukemia vaccines.\n\nBeyond vaccinations, regular veterinary checkups should include physical examinations, dental assessments, parasite screening, and bloodwork for senior pets or those with health conditions. Adult pets need annual wellness exams, while senior pets (7+ years for dogs, 10+ for cats) benefit from twice-yearly checkups. Preventive dental care is crucial, as dental disease affects 80% of dogs and 70% of cats over age three and can lead to serious health problems.\n\nEstablish a year-round parasite prevention program for fleas, ticks, heartworms, and intestinal parasites. Many products provide multi-parasite protection in convenient monthly treatments. Keep detailed records of all vaccinations, treatments, and veterinary visits. Set reminders for upcoming appointments and prescription refills. Invest in pet insurance or maintain an emergency fund to cover unexpected health issues. Proactive healthcare and maintaining vaccination schedules ensure your pet lives a long, healthy life.',
            category: 'post-adoption',
            orderIndex: 2,
            createdAt: new Date(),
        },
        {
            title: 'Training and Socialization Tips',
            content: 'Training and socialization are foundational to developing a well-adjusted, well-behaved pet and strengthening your bond. Start training immediately after bringing your pet home, using positive reinforcement methods that reward desired behaviors with treats, praise, and play. Avoid punishment-based training, which can damage trust and create fear or aggression. Consistency is key – all family members should use the same commands and rules to avoid confusing your pet.\n\nBasic obedience training teaches essential commands like sit, stay, come, down, and leave it. These commands provide safety, enable better communication, and make daily life more manageable. Practice training sessions in short, focused intervals of 5-10 minutes, several times daily. Dogs, especially, thrive on mental stimulation that training provides. Many communities offer group training classes, which have the added benefit of socializing your dog with other animals and people in a controlled environment.\n\nSocialization involves exposing your pet to various people, animals, environments, sounds, and experiences in a positive, controlled manner. Proper socialization during the critical period (3-14 weeks for puppies, 3-9 weeks for kittens) is ideal, but adult animals also benefit from gradual exposure to new experiences. Introduce new situations slowly, always keeping experiences positive. If your pet shows fear or stress, slow down and create more positive associations before progressing.\n\nAddress behavioral issues promptly with professional help if needed. Common challenges include separation anxiety, excessive barking, destructive chewing, aggression, litter box problems, or fearfulness. Certified professional dog trainers or veterinary behaviorists can provide guidance tailored to your specific situation. Remember that behavioral modification takes time, patience, and consistency. The investment in training and socialization pays lifelong dividends in a happy, confident, well-mannered pet.',
            category: 'post-adoption',
            orderIndex: 3,
            createdAt: new Date(),
        },
        {
            title: 'Long-term Care and Commitment',
            content: 'Pet adoption is a long-term commitment requiring dedication through all life stages and circumstances. Dogs typically live 10-15 years, cats 12-20 years, meaning your pet will be part of your family through major life changes. Understanding this commitment before adoption helps ensure you are prepared for the responsibilities and joys of long-term pet ownership.\n\nAs pets age, their needs evolve. Young animals require extensive training, socialization, and high energy outlets. Adult pets often settle into comfortable routines but still need regular exercise, mental stimulation, and veterinary care. Senior pets may develop health issues requiring more frequent veterinary visits, medications, special diets, and mobility assistance. Each life stage brings unique challenges and rewards, and responsible pet owners adapt their care accordingly.\n\nFinancial commitment extends throughout your pet\'s lifetime. Budget for routine care, unexpected emergencies, and increasing medical needs as pets age. Senior pets often require more expensive care including bloodwork, medications, and treatment for chronic conditions like arthritis, diabetes, or kidney disease. Pet insurance or dedicated savings accounts help manage these costs. Consider long-term financial planning for your pet as you would for any family member.\n\nLife circumstances change, but your commitment to your pet should remain constant. Job changes, moves, relationship changes, and new family members can all impact pet ownership. Plan for these contingencies and prioritize your pet\'s wellbeing during transitions. If you must rehome a pet due to truly unavoidable circumstances, work with reputable rescues and follow your adoption contract terms rather than giving away pets on social media or abandoning them. Remember that when you adopt, you become responsible for a living being depending on you for care, love, and protection throughout their entire life.',
            category: 'post-adoption',
            orderIndex: 4,
            createdAt: new Date(),
        },
    ];

    await db.insert(adoptionGuides).values(sampleGuides);
    
    console.log('✅ Adoption guides seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});