import { db } from '@/db';
import { animalShelters } from '@/db/schema';

async function main() {
    const currentDate = new Date().toISOString();
    
    const sampleShelters = [
        {
            name: 'Friendicoes Shelter',
            description: 'Premier animal shelter with comprehensive facilities',
            address: 'Jangpura Extension, New Delhi',
            city: 'New Delhi',
            state: 'Delhi',
            phone: '+91-11-24310307',
            email: 'shelter@friendicoes.org',
            website: 'https://friendicoes.org/shelter',
            capacity: 500,
            currentAnimals: 420,
            facilities: ['veterinary clinic', 'surgery room', 'isolation ward', 'adoption center', 'grooming'],
            verified: true,
            rating: 4.8,
            createdAt: currentDate,
            updatedAt: currentDate,
        },
        {
            name: 'PFA Adoption Center',
            description: 'Large adoption center for rescued animals',
            address: 'Chattarpur, South Delhi',
            city: 'New Delhi',
            state: 'Delhi',
            phone: '+91-11-26811200',
            email: 'adoption@peopleforanimalsindia.org',
            website: null,
            capacity: 300,
            currentAnimals: 265,
            facilities: ['adoption center', 'medical clinic', 'quarantine area', 'play yards'],
            verified: true,
            rating: 4.7,
            createdAt: currentDate,
            updatedAt: currentDate,
        },
        {
            name: 'Delhi SPCA Shelter',
            description: 'Society for Prevention of Cruelty to Animals shelter',
            address: 'Vasant Vihar, New Delhi',
            city: 'New Delhi',
            state: 'Delhi',
            phone: '+91-11-41234567',
            email: 'delhispca@shelter.org',
            website: null,
            capacity: 200,
            currentAnimals: 178,
            facilities: ['shelter', 'clinic', 'adoption services', 'education center'],
            verified: true,
            rating: 4.6,
            createdAt: currentDate,
            updatedAt: currentDate,
        },
        {
            name: 'Sanjay Gandhi Animal Care Centre',
            description: 'Government-run shelter with extensive capacity',
            address: 'Rajpur Khurd Extension, New Delhi',
            city: 'New Delhi',
            state: 'Delhi',
            phone: '+91-11-27887439',
            email: 'sgacchelter@delhi.gov.in',
            website: null,
            capacity: 1000,
            currentAnimals: 850,
            facilities: ['large shelter', 'veterinary hospital', 'sterilization unit', 'rescue vehicles'],
            verified: true,
            rating: 4.5,
            createdAt: currentDate,
            updatedAt: currentDate,
        },
        {
            name: 'Animal Care Trust Shelter',
            description: 'Non-profit shelter focusing on rehabilitation',
            address: 'Safdarjung Enclave, New Delhi',
            city: 'New Delhi',
            state: 'Delhi',
            phone: '+91-11-26567890',
            email: 'act@animalshelter.org',
            website: null,
            capacity: 150,
            currentAnimals: 132,
            facilities: ['shelter', 'medical care', 'foster network', 'adoption'],
            verified: true,
            rating: 4.4,
            createdAt: currentDate,
            updatedAt: currentDate,
        },
        {
            name: 'Hope & Home For Animals',
            description: 'Modern shelter with focus on adoption',
            address: 'Dwarka Sector 12, New Delhi',
            city: 'New Delhi',
            state: 'Delhi',
            phone: '+91-11-28765432',
            email: 'hope@animalshome.org',
            website: null,
            capacity: 100,
            currentAnimals: 85,
            facilities: ['shelter', 'clinic', 'grooming', 'training area'],
            verified: true,
            rating: 4.6,
            createdAt: currentDate,
            updatedAt: currentDate,
        },
        {
            name: 'Street Tails Rescue Shelter',
            description: 'Rescue shelter for street animals',
            address: 'Rohini Sector 15, New Delhi',
            city: 'New Delhi',
            state: 'Delhi',
            phone: '+91-11-27654321',
            email: 'streettails@rescue.org',
            website: null,
            capacity: 80,
            currentAnimals: 72,
            facilities: ['shelter', 'medical unit', 'rehabilitation center'],
            verified: false,
            rating: 4.3,
            createdAt: currentDate,
            updatedAt: currentDate,
        },
        {
            name: 'Paws & Claws Shelter',
            description: 'Community-run shelter for abandoned pets',
            address: 'Mayur Vihar Phase 1, New Delhi',
            city: 'New Delhi',
            state: 'Delhi',
            phone: '+91-11-22345678',
            email: 'pawsandclaws@shelter.org',
            website: null,
            capacity: 120,
            currentAnimals: 98,
            facilities: ['shelter', 'veterinary care', 'adoption center', 'volunteer training'],
            verified: true,
            rating: 4.5,
            createdAt: currentDate,
            updatedAt: currentDate,
        },
        {
            name: 'Furry Friends Foundation Shelter',
            description: 'Family-friendly adoption shelter',
            address: 'Janakpuri District Centre, New Delhi',
            city: 'New Delhi',
            state: 'Delhi',
            phone: '+91-11-25432109',
            email: 'furry@foundation.org',
            website: null,
            capacity: 90,
            currentAnimals: 76,
            facilities: ['shelter', 'play areas', 'adoption lounge', 'medical room'],
            verified: true,
            rating: 4.4,
            createdAt: currentDate,
            updatedAt: currentDate,
        },
        {
            name: 'Delhi Dog Home',
            description: 'Historic shelter specializing in dogs',
            address: 'Ashram, New Delhi',
            city: 'New Delhi',
            state: 'Delhi',
            phone: '+91-11-23456780',
            email: 'dogshome@delhi.org',
            website: null,
            capacity: 250,
            currentAnimals: 210,
            facilities: ['large kennels', 'veterinary clinic', 'training ground', 'adoption center'],
            verified: true,
            rating: 4.7,
            createdAt: currentDate,
            updatedAt: currentDate,
        },
        {
            name: 'Animal Haven Shelter',
            description: 'Urban shelter with modern facilities',
            address: 'Karol Bagh, New Delhi',
            city: 'New Delhi',
            state: 'Delhi',
            phone: '+91-11-25876543',
            email: 'haven@animalshelter.org',
            website: null,
            capacity: 110,
            currentAnimals: 95,
            facilities: ['shelter', 'clinic', 'isolation rooms', 'adoption area'],
            verified: true,
            rating: 4.5,
            createdAt: currentDate,
            updatedAt: currentDate,
        },
        {
            name: 'Second Chance Animal Shelter',
            description: 'Rehabilitation-focused shelter for injured animals',
            address: 'Saket, New Delhi',
            city: 'New Delhi',
            state: 'Delhi',
            phone: '+91-11-26789012',
            email: 'secondchance@shelter.org',
            website: null,
            capacity: 130,
            currentAnimals: 115,
            facilities: ['rehabilitation center', 'surgery unit', 'recovery rooms', 'adoption services'],
            verified: true,
            rating: 4.6,
            createdAt: currentDate,
            updatedAt: currentDate,
        }
    ];

    await db.insert(animalShelters).values(sampleShelters as any);
    
    console.log('✅ Animal shelters seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});