import { db } from '@/db';
import { ngos } from '@/db/schema';

async function main() {
    const sampleNGOs = [
        {
            name: 'People For Animals (PFA) Delhi',
            description: "India's largest animal welfare organization",
            address: 'Chattarpur, South Delhi',
            city: 'New Delhi',
            state: 'Delhi',
            phone: '+91-11-26811200',
            email: 'pfa.delhi@peopleforanimalsindia.org',
            website: null,
            workingHours: 'Mon-Sat: 9:00 AM - 5:00 PM',
            specialization: ['rescue', 'veterinary care', 'adoption', 'animal rights advocacy'],
            verified: true,
            rating: 4.8,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Friendicoes SECA',
            description: "Delhi's oldest animal welfare organization dedicated to rescuing and rehabilitating stray animals",
            address: 'Jangpura Extension, New Delhi',
            city: 'New Delhi',
            state: 'Delhi',
            phone: '+91-11-24310307',
            email: 'info@friendicoes.org',
            website: 'https://friendicoes.org',
            workingHours: 'Daily: 10:00 AM - 6:00 PM',
            specialization: ['emergency rescue', 'medical care', 'sterilization', 'adoption'],
            verified: true,
            rating: 4.7,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Sanjay Gandhi Animal Care Centre',
            description: 'Government-run animal care facility providing comprehensive welfare services',
            address: 'Rajpur Khurd, New Delhi',
            city: 'New Delhi',
            state: 'Delhi',
            phone: '+91-11-27887439',
            email: 'sgacc@delhi.gov.in',
            website: null,
            workingHours: 'Daily: 8:00 AM - 8:00 PM',
            specialization: ['sterilization', 'vaccination', 'treatment', 'shelter'],
            verified: true,
            rating: 4.5,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Wildlife SOS',
            description: 'Leading wildlife conservation organization working to protect Indian wildlife',
            address: 'Lodhi Road, New Delhi',
            city: 'New Delhi',
            state: 'Delhi',
            phone: '+91-9871963535',
            email: 'info@wildlifesos.org',
            website: 'https://wildlifesos.org',
            workingHours: 'Mon-Sat: 10:00 AM - 5:00 PM',
            specialization: ['wildlife rescue', 'rehabilitation', 'conservation', 'education'],
            verified: true,
            rating: 4.9,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Help Animals India',
            description: 'Focused on street animal welfare and rescue operations',
            address: 'Greater Kailash, South Delhi',
            city: 'New Delhi',
            state: 'Delhi',
            phone: '+91-11-41234567',
            email: 'contact@helpanimalsindia.org',
            website: null,
            workingHours: 'Mon-Sun: 9:00 AM - 7:00 PM',
            specialization: ['street animal care', 'feeding programs', 'medical aid', 'adoption'],
            verified: true,
            rating: 4.6,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Dhyan Foundation Animal Care',
            description: 'Spiritual organization dedicated to animal welfare and care',
            address: 'Vasant Kunj, New Delhi',
            city: 'New Delhi',
            state: 'Delhi',
            phone: '+91-9871084864',
            email: 'animalcare@dhyanfoundation.com',
            website: null,
            workingHours: 'Daily: 7:00 AM - 7:00 PM',
            specialization: ['feeding', 'medical care', 'rescue', 'awareness'],
            verified: true,
            rating: 4.4,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Red Paws Rescue',
            description: 'Emergency response team for injured and abandoned animals',
            address: 'Defence Colony, New Delhi',
            city: 'New Delhi',
            state: 'Delhi',
            phone: '+91-11-29876543',
            email: 'redpawsrescue@gmail.com',
            website: null,
            workingHours: '24/7 Emergency Services',
            specialization: ['emergency rescue', 'trauma care', 'foster program', 'adoption'],
            verified: true,
            rating: 4.7,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Animal Aid Unlimited - Delhi Branch',
            description: 'Providing street animal rescue and medical care',
            address: 'Hauz Khas, New Delhi',
            city: 'New Delhi',
            state: 'Delhi',
            phone: '+91-11-41567890',
            email: 'animalaidunlimited@gmail.com',
            website: null,
            workingHours: 'Daily: 9:00 AM - 6:00 PM',
            specialization: ['street rescue', 'surgery', 'rehabilitation', 'sanctuary'],
            verified: true,
            rating: 4.8,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Karma Animal Welfare',
            description: 'Community-based animal welfare organization',
            address: 'Lajpat Nagar, South Delhi',
            city: 'New Delhi',
            state: 'Delhi',
            phone: '+91-98765-43210',
            email: 'karmaanimalwelfare@gmail.com',
            website: null,
            workingHours: 'Mon-Fri: 10:00 AM - 5:00 PM',
            specialization: ['community outreach', 'feeding programs', 'medical camps', 'sterilization'],
            verified: false,
            rating: 4.3,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Street Dogs of India',
            description: 'Dedicated to improving lives of street dogs across Delhi',
            address: 'Nehru Place, New Delhi',
            city: 'New Delhi',
            state: 'Delhi',
            phone: '+91-11-23456789',
            email: 'info@streetdogsofindia.org',
            website: 'https://streetdogsofindia.org',
            workingHours: 'Mon-Sun: 8:00 AM - 8:00 PM',
            specialization: ['street dog care', 'vaccination drives', 'feeding', 'sterilization'],
            verified: true,
            rating: 4.5,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Animal Welfare Board of India',
            description: 'Statutory advisory body for animal welfare policies',
            address: 'Pocket 1, Jasola, New Delhi',
            city: 'New Delhi',
            state: 'Delhi',
            phone: '+91-11-23070327',
            email: 'awbi@nic.in',
            website: 'https://awbi.org',
            workingHours: 'Mon-Fri: 9:30 AM - 6:00 PM',
            specialization: ['policy advocacy', 'welfare programs', 'training', 'funding'],
            verified: true,
            rating: 4.6,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Fauna Police',
            description: 'Wildlife protection and animal rights enforcement',
            address: 'Greater Kailash II, New Delhi',
            city: 'New Delhi',
            state: 'Delhi',
            phone: '+91-11-29552965',
            email: 'info@faunapolice.org',
            website: 'https://faunapolice.org',
            workingHours: 'Mon-Fri: 9:00 AM - 6:00 PM',
            specialization: ['wildlife protection', 'legal intervention', 'abuse reporting', 'awareness'],
            verified: true,
            rating: 4.5,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        }
    ];

    await db.insert(ngos).values(sampleNGOs);
    
    console.log('✅ NGOs seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});