import { db } from '@/db';
import { pets } from '@/db/schema';

async function main() {
    const newPets = [
        {
            name: 'Moti',
            species: 'Dog',
            breed: 'Indian Indie',
            age: '2 years',
            gender: 'Male',
            description: 'Moti is a friendly and loyal street dog who loves human companionship. He is great with children and would make an excellent family pet. House-trained and knows basic commands.',
            medical_history: 'Fully recovered from minor skin infection. No major health issues.',
            vaccination_status: 'Rabies and DHPPi vaccinated. Valid until March 2025.',
            adoption_status: 'available',
            shelter_id: 3,
            image_url: null,
            special_needs: null,
            created_at: new Date('2024-02-15').toISOString(),
        },
        {
            name: 'Chhotu',
            species: 'Dog',
            breed: 'Indian Pariah',
            age: '6 months',
            gender: 'Male',
            description: 'Energetic puppy with a playful nature. Chhotu is very intelligent and learns quickly. He needs an active family who can give him plenty of exercise and mental stimulation.',
            medical_history: 'Healthy puppy with no medical issues.',
            vaccination_status: 'First round of vaccinations completed. Second round due in April 2024.',
            adoption_status: 'available',
            shelter_id: 1,
            image_url: null,
            special_needs: 'Needs regular playtime and socialization',
            created_at: new Date('2024-03-01').toISOString(),
        },
        {
            name: 'Simba',
            species: 'Dog',
            breed: 'Labrador Mix',
            age: '3 years',
            gender: 'Male',
            description: 'Simba is a gentle giant who loves water and fetch games. He is well-trained and perfect for families with a backyard. Gets along well with other dogs.',
            medical_history: 'Hip dysplasia monitored regularly. Currently on joint supplements.',
            vaccination_status: 'All vaccinations up to date. Valid until June 2025.',
            adoption_status: 'available',
            shelter_id: 5,
            image_url: null,
            special_needs: 'Requires joint supplements and moderate exercise',
            created_at: new Date('2024-01-20').toISOString(),
        },
        {
            name: 'Kalu',
            species: 'Dog',
            breed: 'Indian Indie',
            age: '4 years',
            gender: 'Male',
            description: 'Calm and protective, Kalu is an excellent guard dog who is fiercely loyal to his family. Best suited for experienced dog owners who can provide firm but gentle guidance.',
            medical_history: 'No significant health issues. Regular deworming done.',
            vaccination_status: 'Fully vaccinated. Rabies vaccine valid until August 2024.',
            adoption_status: 'available',
            shelter_id: 7,
            image_url: null,
            special_needs: null,
            created_at: new Date('2024-02-05').toISOString(),
        },
        {
            name: 'Pinky',
            species: 'Dog',
            breed: 'Pomeranian',
            age: '1 year',
            gender: 'Female',
            description: 'Adorable and fluffy, Pinky is a sweet-natured companion dog. She loves cuddles and is perfect for apartment living. Great with seniors and first-time dog owners.',
            medical_history: 'Minor dental issue treated. Regular dental care recommended.',
            vaccination_status: 'All core vaccines administered. Valid until December 2024.',
            adoption_status: 'pending',
            shelter_id: 2,
            image_url: null,
            special_needs: 'Requires regular grooming every 6 weeks',
            created_at: new Date('2024-02-28').toISOString(),
        },
        {
            name: 'Bruno',
            species: 'Dog',
            breed: 'Indian Spitz',
            age: '2 years',
            gender: 'Male',
            description: 'Bruno is an alert and vocal dog who makes an excellent watchdog. He is very attached to his family and thrives on attention. Good with older children.',
            medical_history: 'Healthy with regular vet checkups.',
            vaccination_status: 'Rabies, DHPPi, and bordetella vaccines current. Valid until May 2025.',
            adoption_status: 'available',
            shelter_id: 4,
            image_url: null,
            special_needs: null,
            created_at: new Date('2024-01-10').toISOString(),
        },
        {
            name: 'Sheru',
            species: 'Dog',
            breed: 'Indian Pariah',
            age: '5 years',
            gender: 'Male',
            description: 'Senior dog with a calm demeanor and lots of love to give. Sheru prefers a quiet home environment and makes an ideal companion for seniors. Very low maintenance.',
            medical_history: 'Arthritis in hind legs managed with medication.',
            vaccination_status: 'All vaccinations current. Next due in September 2024.',
            adoption_status: 'available',
            shelter_id: 9,
            image_url: null,
            special_needs: 'Requires daily arthritis medication and soft bedding',
            created_at: new Date('2024-01-25').toISOString(),
        },
        {
            name: 'Lucky',
            species: 'Dog',
            breed: 'Cocker Spaniel Mix',
            age: '3 years',
            gender: 'Female',
            description: 'Gentle and affectionate, Lucky loves everyone she meets. She has beautiful golden fur and soulful eyes. Perfect family pet who is great with children and other pets.',
            medical_history: 'Ear infections common to breed. Requires regular ear cleaning.',
            vaccination_status: 'Fully vaccinated. Rabies vaccine valid until July 2025.',
            adoption_status: 'available',
            shelter_id: 6,
            image_url: null,
            special_needs: 'Weekly ear cleaning required',
            created_at: new Date('2024-02-10').toISOString(),
        },
        {
            name: 'Tiger',
            species: 'Dog',
            breed: 'Indian Indie',
            age: '1 year',
            gender: 'Male',
            description: 'High-energy young dog who needs an active lifestyle. Tiger loves running, hiking, and outdoor adventures. Best for athletic owners who can keep up with his energy.',
            medical_history: 'No health issues. Very fit and healthy.',
            vaccination_status: 'All puppy vaccines completed. Adult boosters due in April 2024.',
            adoption_status: 'available',
            shelter_id: 8,
            image_url: null,
            special_needs: 'Requires minimum 2 hours daily exercise',
            created_at: new Date('2024-03-05').toISOString(),
        },
        {
            name: 'Laila',
            species: 'Dog',
            breed: 'Dachshund',
            age: '4 years',
            gender: 'Female',
            description: 'Charming sausage dog with a big personality. Laila is independent yet affectionate. She loves burrow under blankets and is perfect for someone looking for a smaller companion dog.',
            medical_history: 'Back issues monitored due to breed predisposition. Currently healthy.',
            vaccination_status: 'All vaccines up to date. Valid until October 2024.',
            adoption_status: 'available',
            shelter_id: 10,
            image_url: null,
            special_needs: 'Avoid jumping from heights, ramp or stairs recommended',
            created_at: new Date('2024-01-15').toISOString(),
        },
        {
            name: 'Rocky',
            species: 'Dog',
            breed: 'Pug',
            age: '2 years',
            gender: 'Male',
            description: 'Sweet-faced Rocky is a lovable couch potato. He enjoys short walks and lots of naps. Great for apartment living and perfect for someone who wants a low-energy companion.',
            medical_history: 'Breathing issues typical of breed. Monitored by vet regularly.',
            vaccination_status: 'Fully vaccinated. Rabies valid until November 2024.',
            adoption_status: 'pending',
            shelter_id: 3,
            image_url: null,
            special_needs: 'Requires air-conditioned environment, avoid hot weather exercise',
            created_at: new Date('2024-02-20').toISOString(),
        },
        {
            name: 'Buddy',
            species: 'Dog',
            breed: 'Labrador',
            age: '6 months',
            gender: 'Male',
            description: 'Adorable lab puppy with typical puppy energy and enthusiasm. Buddy is food-motivated which makes training easy. He will grow into a large dog and needs space to run.',
            medical_history: 'Healthy puppy. Recent checkup shows no issues.',
            vaccination_status: 'Puppy vaccination series in progress. Next shot due in April 2024.',
            adoption_status: 'available',
            shelter_id: 1,
            image_url: null,
            special_needs: 'Puppy training and socialization classes recommended',
            created_at: new Date('2024-03-08').toISOString(),
        },
        {
            name: 'Shiro',
            species: 'Dog',
            breed: 'Shih Tzu',
            age: '3 years',
            gender: 'Female',
            description: 'Beautiful long-haired companion who loves being pampered. Shiro is gentle and quiet, making her perfect for apartment living. She enjoys leisurely walks and cuddle time.',
            medical_history: 'History of eye infections. Requires daily eye cleaning.',
            vaccination_status: 'All vaccinations current. Valid until January 2025.',
            adoption_status: 'available',
            shelter_id: 5,
            image_url: null,
            special_needs: 'Daily eye cleaning and professional grooming every 6-8 weeks',
            created_at: new Date('2024-01-30').toISOString(),
        },
        {
            name: 'Raju',
            species: 'Dog',
            breed: 'Indian Indie',
            age: '7 years',
            gender: 'Male',
            description: 'Senior street dog who deserves a comfortable retirement home. Raju is calm, house-trained, and extremely grateful for any kindness shown. He is perfect for someone wanting a mature, settled dog.',
            medical_history: 'Age-related issues including mild cataracts. Overall good health for his age.',
            vaccination_status: 'All vaccines up to date. Rabies valid until June 2024.',
            adoption_status: 'available',
            shelter_id: 7,
            image_url: null,
            special_needs: 'Senior dog requiring soft food and regular vet checkups',
            created_at: new Date('2024-02-01').toISOString(),
        },
        {
            name: 'Chintu',
            species: 'Dog',
            breed: 'Indian Pariah',
            age: '8 months',
            gender: 'Male',
            description: 'Playful teenage pup who is still learning manners. Chintu is smart and eager to please. He would benefit from obedience training and consistent guidance from his new family.',
            medical_history: 'No health issues. Growing well.',
            vaccination_status: 'Completed primary vaccination series. Next booster due in May 2024.',
            adoption_status: 'available',
            shelter_id: 2,
            image_url: null,
            special_needs: 'Requires basic obedience training',
            created_at: new Date('2024-02-25').toISOString(),
        },
        {
            name: 'Brownie',
            species: 'Dog',
            breed: 'Indian Indie',
            age: '2 years',
            gender: 'Female',
            description: 'Sweet-natured female dog who is especially good with children. Brownie is patient and gentle, making her an ideal family pet. She enjoys being part of all family activities.',
            medical_history: 'Spayed. No health concerns.',
            vaccination_status: 'Fully vaccinated including rabies. Valid until August 2024.',
            adoption_status: 'available',
            shelter_id: 4,
            image_url: null,
            special_needs: null,
            created_at: new Date('2024-01-18').toISOString(),
        },
        {
            name: 'Max',
            species: 'Dog',
            breed: 'Labrador Mix',
            age: '4 years',
            gender: 'Male',
            description: 'Highly trainable and obedient dog who knows multiple commands. Max is great for someone wanting a well-behaved companion. He loves car rides and outdoor activities.',
            medical_history: 'Fully healthy with regular vet visits.',
            vaccination_status: 'All core vaccines current. Valid until September 2024.',
            adoption_status: 'pending',
            shelter_id: 9,
            image_url: null,
            special_needs: null,
            created_at: new Date('2024-02-12').toISOString(),
        },
        {
            name: 'Mitthu',
            species: 'Cat',
            breed: 'Indian Domestic',
            age: '1 year',
            gender: 'Male',
            description: 'Playful and curious cat who loves climbing and exploring. Mitthu is litter-trained and gets along well with other cats. Perfect for someone who wants an entertaining feline companion.',
            medical_history: 'Neutered. No health issues.',
            vaccination_status: 'FVRCP vaccine completed. Valid until December 2024.',
            adoption_status: 'available',
            shelter_id: 6,
            image_url: null,
            special_needs: null,
            created_at: new Date('2024-02-18').toISOString(),
        },
        {
            name: 'Whiskers',
            species: 'Cat',
            breed: 'Persian',
            age: '3 years',
            gender: 'Female',
            description: 'Gorgeous Persian cat with long, luxurious fur. Whiskers is a calm indoor cat who enjoys quiet environments. She is affectionate with her chosen people and loves being groomed.',
            medical_history: 'History of hairballs. Requires regular brushing.',
            vaccination_status: 'All vaccinations up to date. Valid until July 2024.',
            adoption_status: 'available',
            shelter_id: 8,
            image_url: null,
            special_needs: 'Daily brushing required, hairball prevention diet recommended',
            created_at: new Date('2024-01-22').toISOString(),
        },
        {
            name: 'Billo',
            species: 'Cat',
            breed: 'Indian Domestic',
            age: '6 months',
            gender: 'Female',
            description: 'Adorable kitten with striking eyes and a friendly personality. Billo loves to play and is very social. She would do well in a home with or without other pets.',
            medical_history: 'Healthy kitten with no medical issues.',
            vaccination_status: 'First round of kitten vaccines done. Second round due in April 2024.',
            adoption_status: 'available',
            shelter_id: 10,
            image_url: null,
            special_needs: null,
            created_at: new Date('2024-03-02').toISOString(),
        },
        {
            name: 'Meow',
            species: 'Cat',
            breed: 'Indian Domestic',
            age: '2 years',
            gender: 'Male',
            description: 'Independent yet affectionate cat who enjoys his alone time. Meow is perfect for someone who wants a low-maintenance pet. He is quiet and well-behaved.',
            medical_history: 'Neutered. Minor dental cleaning done last month.',
            vaccination_status: 'Rabies and FVRCP current. Valid until October 2024.',
            adoption_status: 'available',
            shelter_id: 3,
            image_url: null,
            special_needs: null,
            created_at: new Date('2024-02-08').toISOString(),
        },
        {
            name: 'Fluffy',
            species: 'Cat',
            breed: 'Persian Mix',
            age: '4 years',
            gender: 'Female',
            description: 'Beautiful semi-longhaired cat with a gentle disposition. Fluffy is best suited for adults only as she can be shy around children. She enjoys sunny windowsills and quiet companionship.',
            medical_history: 'Spayed. Regular checkups show no health concerns.',
            vaccination_status: 'All vaccines up to date. Valid until March 2025.',
            adoption_status: 'available',
            shelter_id: 1,
            image_url: null,
            special_needs: 'Requires adult-only home, weekly brushing',
            created_at: new Date('2024-01-28').toISOString(),
        },
        {
            name: 'Mithu',
            species: 'Bird',
            breed: 'Alexandrine Parrot',
            age: '2 years',
            gender: 'Male',
            description: 'Intelligent and talkative parrot who can mimic several words. Mithu needs an experienced bird owner who can provide mental stimulation and social interaction. He is very social and bonds strongly with his caretaker.',
            medical_history: 'Healthy bird with regular wing and beak trimming.',
            vaccination_status: 'Avian health check completed. Next checkup due in May 2024.',
            adoption_status: 'available',
            shelter_id: 5,
            image_url: null,
            special_needs: 'Large cage, daily out-of-cage time, varied diet with fresh fruits',
            created_at: new Date('2024-02-14').toISOString(),
        },
        {
            name: 'Tweety',
            species: 'Bird',
            breed: 'Lovebird',
            age: '1 year',
            gender: 'Female',
            description: 'Colorful and energetic lovebird who enjoys chirping and playing. Tweety is relatively quiet compared to larger parrots. She does well as a single bird with plenty of human interaction.',
            medical_history: 'No health issues. Regular avian vet checkups.',
            vaccination_status: 'Health check current. Next due in June 2024.',
            adoption_status: 'available',
            shelter_id: 7,
            image_url: null,
            special_needs: 'Needs toys for mental stimulation, fresh water daily',
            created_at: new Date('2024-02-22').toISOString(),
        },
        {
            name: 'Snowball',
            species: 'Rabbit',
            breed: 'Dutch Rabbit',
            age: '1 year',
            gender: 'Male',
            description: 'Gentle rabbit with beautiful black and white markings. Snowball is litter-trained and enjoys hopping around. He needs a spacious enclosure and daily exercise time.',
            medical_history: 'Neutered. Teeth checked regularly for proper length.',
            vaccination_status: 'Rabbit hemorrhagic disease vaccine current. Valid until November 2024.',
            adoption_status: 'available',
            shelter_id: 2,
            image_url: null,
            special_needs: 'Requires hay-based diet, nail trimming every 6 weeks',
            created_at: new Date('2024-02-04').toISOString(),
        },
    ];

    await db.insert(pets).values(newPets);
    
    console.log('✅ Successfully seeded 25 new adoptable pets to the database');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});