import { db } from '@/db';
import { rescueReportsNew } from '@/db/schema';

async function main() {
    const sampleRescueReports = [
        {
            userId: 1,
            animalType: 'Dog',
            location: 'Connaught Place, New Delhi',
            latitude: 28.6315,
            longitude: 77.2167,
            description: 'Injured stray dog with visible leg wound, limping badly near Metro Station Gate 2. Appears to be in severe pain and needs immediate medical attention. Dog is friendly but scared.',
            urgency: 'critical',
            status: 'in_progress',
            imageUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=800',
            phone: '+91-987-654-3210',
            email: 'rescue1@gmail.com',
            assignedNgoId: 2,
            createdAt: new Date('2024-11-25T10:30:00').getTime(),
            updatedAt: new Date('2024-11-25T14:20:00').getTime(),
        },
        {
            userId: 2,
            animalType: 'Cat',
            location: 'Rohini Sector 7, Delhi',
            latitude: 28.7041,
            longitude: 77.1025,
            description: 'Mother cat with 4 newborn kittens found in abandoned building. Kittens are weak and mother appears malnourished. Need shelter and food urgently.',
            urgency: 'high',
            status: 'pending',
            imageUrl: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=800',
            phone: '+91-988-765-4321',
            email: 'concerned.citizen@yahoo.com',
            assignedNgoId: null,
            createdAt: new Date('2024-11-27T08:15:00').getTime(),
            updatedAt: new Date('2024-11-27T08:15:00').getTime(),
        },
        {
            userId: null,
            animalType: 'Cow',
            location: 'Dwarka Sector 10, Delhi',
            latitude: 28.5921,
            longitude: 77.0460,
            description: 'Injured cow lying on main road, hit by vehicle. Bleeding from multiple wounds. Creating traffic hazard and needs immediate rescue and veterinary care.',
            urgency: 'critical',
            status: 'in_progress',
            imageUrl: null,
            phone: '+91-976-543-2109',
            email: 'emergency.help@gmail.com',
            assignedNgoId: 4,
            createdAt: new Date('2024-11-28T06:45:00').getTime(),
            updatedAt: new Date('2024-11-28T09:30:00').getTime(),
        },
        {
            userId: 3,
            animalType: 'Dog',
            location: 'Vasant Kunj Sector C, New Delhi',
            latitude: 28.5244,
            longitude: 77.1586,
            description: 'Abandoned puppy litter of 5, approximately 3 weeks old. Found in cardboard box near shopping complex. Puppies are cold and hungry, need immediate care.',
            urgency: 'high',
            status: 'resolved',
            imageUrl: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800',
            phone: '+91-965-432-1098',
            email: 'animal.lover23@gmail.com',
            assignedNgoId: 1,
            createdAt: new Date('2024-11-20T15:20:00').getTime(),
            updatedAt: new Date('2024-11-22T11:45:00').getTime(),
        },
        {
            userId: 4,
            animalType: 'Bird',
            location: 'Lajpat Nagar Central Market, Delhi',
            latitude: 28.5677,
            longitude: 77.2434,
            description: 'Injured pigeon with broken wing found near market entrance. Bird unable to fly and vulnerable to street animals. Needs rescue and rehabilitation.',
            urgency: 'medium',
            status: 'pending',
            imageUrl: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800',
            phone: '+91-954-321-0987',
            email: 'bird.rescue.delhi@outlook.com',
            assignedNgoId: 3,
            createdAt: new Date('2024-11-26T12:00:00').getTime(),
            updatedAt: new Date('2024-11-26T12:00:00').getTime(),
        },
        {
            userId: 5,
            animalType: 'Dog',
            location: 'Saket District Centre, Delhi',
            latitude: 28.5244,
            longitude: 77.2066,
            description: 'Aggressive stray dog pack of 4-5 dogs near residential area. Residents concerned about safety. Dogs need relocation to safe area and sterilization.',
            urgency: 'high',
            status: 'in_progress',
            imageUrl: null,
            phone: '+91-943-210-9876',
            email: 'rwa.saket@gmail.com',
            assignedNgoId: 5,
            createdAt: new Date('2024-11-24T16:30:00').getTime(),
            updatedAt: new Date('2024-11-25T10:15:00').getTime(),
        },
        {
            userId: null,
            animalType: 'Cat',
            location: 'Karol Bagh Metro Station, Delhi',
            latitude: 28.6519,
            longitude: 77.1904,
            description: 'Kitten trapped in metro station ventilation shaft. Visible from outside but unreachable. Meowing continuously, appears distressed. Needs technical rescue.',
            urgency: 'critical',
            status: 'pending',
            imageUrl: 'https://images.unsplash.com/photo-1529778873920-4da4926a72c2?w=800',
            phone: '+91-932-109-8765',
            email: 'metro.security@dmrc.org',
            assignedNgoId: 6,
            createdAt: new Date('2024-11-28T13:45:00').getTime(),
            updatedAt: new Date('2024-11-28T13:45:00').getTime(),
        },
        {
            userId: 1,
            animalType: 'Dog',
            location: 'Noida Sector 18, Uttar Pradesh',
            latitude: 28.5706,
            longitude: 77.3272,
            description: 'Paralyzed dog dragging back legs near market area. Appears to have suffered spinal injury. Very friendly, seems like abandoned pet. Urgent medical care needed.',
            urgency: 'critical',
            status: 'resolved',
            imageUrl: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=800',
            phone: '+91-921-098-7654',
            email: 'noida.rescue@gmail.com',
            assignedNgoId: 7,
            createdAt: new Date('2024-11-18T09:20:00').getTime(),
            updatedAt: new Date('2024-11-19T16:30:00').getTime(),
        },
        {
            userId: 2,
            animalType: 'Cow',
            location: 'Gurgaon Cyber Hub, Haryana',
            latitude: 28.4950,
            longitude: 77.0890,
            description: 'Pregnant cow in distress near commercial complex. Appears to be in labor but facing complications. Urgently needs veterinary assistance for safe delivery.',
            urgency: 'critical',
            status: 'in_progress',
            imageUrl: null,
            phone: '+91-910-987-6543',
            email: 'gurgaon.animal.care@gmail.com',
            assignedNgoId: 2,
            createdAt: new Date('2024-11-27T17:00:00').getTime(),
            updatedAt: new Date('2024-11-27T18:30:00').getTime(),
        },
        {
            userId: 3,
            animalType: 'Bird',
            location: 'Hauz Khas Village, Delhi',
            latitude: 28.5494,
            longitude: 77.1927,
            description: 'Parrot with clipped wings abandoned in park. Domesticated bird, cannot survive in wild. Needs immediate rescue and adoption placement.',
            urgency: 'medium',
            status: 'resolved',
            imageUrl: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800',
            phone: '+91-909-876-5432',
            email: 'parrot.lover@hotmail.com',
            assignedNgoId: 3,
            createdAt: new Date('2024-11-22T11:30:00').getTime(),
            updatedAt: new Date('2024-11-23T14:20:00').getTime(),
        },
        {
            userId: null,
            animalType: 'Dog',
            location: 'Pitampura TV Tower, Delhi',
            latitude: 28.6942,
            longitude: 77.1311,
            description: 'Old dog with severe mange and skin infection. Fur falling off, visible sores. Dog is weak and malnourished. Requires medical treatment and shelter.',
            urgency: 'high',
            status: 'pending',
            imageUrl: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=800',
            phone: '+91-898-765-4321',
            email: 'pitampura.residents@gmail.com',
            assignedNgoId: null,
            createdAt: new Date('2024-11-26T14:15:00').getTime(),
            updatedAt: new Date('2024-11-26T14:15:00').getTime(),
        },
        {
            userId: 4,
            animalType: 'Cat',
            location: 'Greater Kailash M Block Market, Delhi',
            latitude: 28.5494,
            longitude: 77.2410,
            description: 'Persian cat found wandering, appears lost. Wearing collar with no tags. Well-groomed, clearly a pet. Owner needs to be located or foster care arranged.',
            urgency: 'low',
            status: 'in_progress',
            imageUrl: 'https://images.unsplash.com/photo-1495360010541-f48722b34f7d?w=800',
            phone: '+91-887-654-3210',
            email: 'gk.petfinder@gmail.com',
            assignedNgoId: 1,
            createdAt: new Date('2024-11-25T10:00:00').getTime(),
            updatedAt: new Date('2024-11-26T09:30:00').getTime(),
        },
        {
            userId: 5,
            animalType: 'Dog',
            location: 'Janakpuri District Centre, Delhi',
            latitude: 28.6217,
            longitude: 77.0864,
            description: 'Labrador mix found tied to tree, abandoned by owner. Dog is dehydrated and distressed. Friendly temperament, needs rehoming urgently.',
            urgency: 'high',
            status: 'resolved',
            imageUrl: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800',
            phone: '+91-876-543-2109',
            email: 'janakpuri.animal.welfare@gmail.com',
            assignedNgoId: 4,
            createdAt: new Date('2024-11-21T08:45:00').getTime(),
            updatedAt: new Date('2024-11-23T15:00:00').getTime(),
        },
        {
            userId: 1,
            animalType: 'Bird',
            location: 'Lodhi Garden, New Delhi',
            latitude: 28.5933,
            longitude: 77.2197,
            description: 'Peacock injured by dog attack in garden. Tail feathers damaged, visible wounds on body. Bird in shock, needs immediate veterinary attention.',
            urgency: 'high',
            status: 'in_progress',
            imageUrl: null,
            phone: '+91-865-432-1098',
            email: 'lodhi.garden.care@gmail.com',
            assignedNgoId: 6,
            createdAt: new Date('2024-11-27T07:30:00').getTime(),
            updatedAt: new Date('2024-11-27T10:15:00').getTime(),
        },
        {
            userId: null,
            animalType: 'Cow',
            location: 'Nehru Place Metro Station, Delhi',
            latitude: 28.5494,
            longitude: 77.2501,
            description: 'Bull with rope embedded in neck causing deep wound. Animal appears to have escaped from somewhere. Wound is infected and requires surgical intervention.',
            urgency: 'critical',
            status: 'pending',
            imageUrl: null,
            phone: '+91-854-321-0987',
            email: 'emergency.cow.rescue@gmail.com',
            assignedNgoId: 7,
            createdAt: new Date('2024-11-28T11:00:00').getTime(),
            updatedAt: new Date('2024-11-28T11:00:00').getTime(),
        },
        {
            userId: 2,
            animalType: 'Dog',
            location: 'Rajouri Garden Main Market, Delhi',
            latitude: 28.6415,
            longitude: 77.1215,
            description: 'Pregnant stray dog about to give birth near busy market. Dog is restless and looking for safe place. Needs immediate shelter and veterinary monitoring.',
            urgency: 'medium',
            status: 'in_progress',
            imageUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=800',
            phone: '+91-843-210-9876',
            email: 'rajouri.animal.friends@gmail.com',
            assignedNgoId: 2,
            createdAt: new Date('2024-11-26T16:20:00').getTime(),
            updatedAt: new Date('2024-11-27T08:45:00').getTime(),
        },
        {
            userId: 3,
            animalType: 'Cat',
            location: 'South Extension Part 1, Delhi',
            latitude: 28.5678,
            longitude: 77.2244,
            description: 'Siamese cat with eye infection, pus discharge visible. Cat is tame, possibly abandoned pet. Needs immediate medical treatment to prevent vision loss.',
            urgency: 'medium',
            status: 'resolved',
            imageUrl: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=800',
            phone: '+91-832-109-8765',
            email: 'southex.rescue@yahoo.com',
            assignedNgoId: 5,
            createdAt: new Date('2024-11-23T13:30:00').getTime(),
            updatedAt: new Date('2024-11-24T17:00:00').getTime(),
        },
        {
            userId: 4,
            animalType: 'Dog',
            location: 'Mayur Vihar Phase 1, Delhi',
            latitude: 28.6089,
            longitude: 77.2984,
            description: 'German Shepherd puppy found on highway service road. Appears lost, wearing expensive collar. Likely escaped from home, needs temporary shelter while owner is located.',
            urgency: 'low',
            status: 'pending',
            imageUrl: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800',
            phone: '+91-821-098-7654',
            email: 'mayurvihar.pets@gmail.com',
            assignedNgoId: null,
            createdAt: new Date('2024-11-27T15:45:00').getTime(),
            updatedAt: new Date('2024-11-27T15:45:00').getTime(),
        },
        {
            userId: 5,
            animalType: 'Bird',
            location: 'INA Market, New Delhi',
            latitude: 28.5677,
            longitude: 77.2067,
            description: 'Owl trapped in fishnet near market area. Bird is entangled and struggling. Requires careful rescue to avoid further injury. Rare species, needs wildlife expert.',
            urgency: 'high',
            status: 'in_progress',
            imageUrl: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800',
            phone: '+91-810-987-6543',
            email: 'wildlife.delhi@gmail.com',
            assignedNgoId: 3,
            createdAt: new Date('2024-11-28T06:00:00').getTime(),
            updatedAt: new Date('2024-11-28T08:30:00').getTime(),
        },
        {
            userId: null,
            animalType: 'Dog',
            location: 'Punjabi Bagh Club Road, Delhi',
            latitude: 28.6692,
            longitude: 77.1314,
            description: 'Street dog hit by motorbike, back leg appears broken. Dog is in pain but conscious. Needs immediate medical attention and x-rays to assess damage.',
            urgency: 'low',
            status: 'pending',
            imageUrl: null,
            phone: '+91-809-876-5432',
            email: 'punjabibagh.help@gmail.com',
            assignedNgoId: null,
            createdAt: new Date('2024-11-28T12:30:00').getTime(),
            updatedAt: new Date('2024-11-28T12:30:00').getTime(),
        },
    ];

    await db.insert(rescueReportsNew).values(sampleRescueReports);
    
    console.log('✅ Rescue reports seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});